### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by euherg** [ob-algdati-ws17/blatt-7-aufgabe-1-forever_alone#2]
ist es normal, dass Trevis nicht alle Tests durchläuft?
Oder ich lese das falsch und es wird jeder File im Test-Ordner (z.B. testAvlTree) als "einen Test" angezeigt?
```
$ make test
Running tests...
Test project /home/travis/build/ob-algdati-ws17/blatt-7-aufgabe-1-forever_alone/build
    Start 1: testAvlTree
1/1 Test #1: testAvlTree ......................   Passed    0.01 sec
100% tests passed, 0 tests failed out of 1
```

**Comment by obcode** [comment]
Da laufen alle die `testAvlTree` heißen.

https://stackoverflow.com/questions/5709914/using-cmake-how-do-i-get-verbose-output-from-ctest
